# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.CharField(max_length=80)),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('moderation_approved', 'Moderation approved'), ('checkout_created', 'Checkout created'), ('authorized', 'Authorized'), ('processing', 'Processing'), ('won', 'Won'), ('outbid', 'Outbid'), ('payment_failed', 'Payment failed'), ('auth_canceled', 'Authorization canceled'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='created', max_length=32)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='accounts.userprofile')),
            ],
        ),
    ]
