# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('boards', '0001_initial'),
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='boards.board'),
        ),
        migrations.AddField(
            model_name='bid',
            name='represented_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fan_bids', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['board', '-created_at'], name='bidding_bid_board_i_99f3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', '-created_at'], name='bidding_bid_bidder__bdfe28_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['represented_school', '-created_at'], name='bidding_bid_represe_7873c3_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status', '-created_at'], name='bidding_bid_status_3b684c_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['stripe_payment_intent_id'], name='bidding_bid_stripe__c814e9_idx'),
        ),
    ]
