# Generated by Django 4.2.27 on 2026-08-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('moderation_approved', 'Moderation approved'), ('checkout_created', 'Checkout created'), ('authorized', 'Authorized'), ('processing', 'Processing'), ('won', 'Won'), ('demo_won', 'Won in local free-play'), ('outbid', 'Outbid'), ('payment_failed', 'Payment failed'), ('auth_canceled', 'Authorization canceled'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='created', max_length=32),
        ),
    ]
