# Generated by Django 5.2.17 on 2026-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_alter_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
