# Generated by Django 5.2 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0002_moderation_controls"),
        ("bidding", "0005_bid_season_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="message_validation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bids",
                to="moderation.messagevalidation",
            ),
        ),
    ]
