# Generated by Django 5.2.17 on 2026-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_favorite_entity'),
        ('bidding', '0007_entity_competition_period'),
        ('boards', '0006_entity_competition_period'),
        ('leaderboard', '0004_remove_competitionperiod_leaderboard_year_e595e7_idx_and_more'),
        ('moderation', '0005_alter_messagevalidation_represented_entity'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'DROP INDEX IF EXISTS "bidding_bid_represe_7873c3_idx"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='bid',
                    name='bidding_bid_represe_7873c3_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='leaderboard.competitionperiod'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='represented_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fan_bids', to='schools.entity'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['represented_entity', '-created_at'], name='bidding_bid_represe_8742e6_idx'),
        ),
    ]
