# Generated by Django 5.2.17 on 2026-08-30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_userprofile_dispute_count_and_more"),
        ("bidding", "0008_remove_bid_bidding_bid_represe_7873c3_idx_and_more"),
        ("boards", "0007_remove_boardtakeover_boards_boar_represe_b9905b_idx_and_more"),
        ("moderation", "0005_alter_messagevalidation_represented_entity"),
        ("schools", "0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BidRiskConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("new_max_bid_cents", models.PositiveIntegerField(default=5000)), ("new_hourly_spend_cents", models.PositiveIntegerField(default=10000)), ("new_daily_spend_cents", models.PositiveIntegerField(default=25000)),
                ("established_max_bid_cents", models.PositiveIntegerField(default=10000)), ("established_hourly_spend_cents", models.PositiveIntegerField(default=25000)), ("established_daily_spend_cents", models.PositiveIntegerField(default=75000)),
                ("trusted_max_bid_cents", models.PositiveIntegerField(default=25000)), ("trusted_hourly_spend_cents", models.PositiveIntegerField(default=50000)), ("trusted_daily_spend_cents", models.PositiveIntegerField(default=150000)),
                ("global_max_bid_cents", models.PositiveIntegerField(default=25000)), ("global_hourly_spend_cents", models.PositiveIntegerField(default=150000)),
                ("high_value_confirmation_threshold_cents", models.PositiveIntegerField(default=5000)), ("very_high_value_confirmation_threshold_cents", models.PositiveIntegerField(default=10000)),
                ("high_value_bidding_enabled", models.BooleanField(default=True)), ("new_user_bidding_enabled", models.BooleanField(default=True)),
                ("payment_failure_limit", models.PositiveIntegerField(default=5)), ("payment_failure_window_minutes", models.PositiveIntegerField(default=30)), ("updated_at", models.DateTimeField(auto_now=True)),
            ], options={"verbose_name": "bid risk configuration", "verbose_name_plural": "bid risk configuration"},
        ),
        migrations.AddField(model_name="bid", name="stripe_dispute_id", field=models.CharField(blank=True, max_length=255, null=True, unique=True)),
        migrations.CreateModel(
            name="BidConfirmation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("message", models.CharField(max_length=80)), ("amount_cents", models.PositiveIntegerField()), ("current_board_amount_cents", models.PositiveIntegerField()), ("pending_challenge_amount_cents", models.PositiveIntegerField(blank=True, null=True)), ("minimum_bid_cents", models.PositiveIntegerField()),
                ("guaranteed_seconds", models.PositiveIntegerField(default=30)), ("confirmation_version", models.CharField(default="bid-confirmation-v1", max_length=50)), ("shown_at", models.DateTimeField(auto_now_add=True)), ("confirmed_at", models.DateTimeField(blank=True, null=True)), ("expires_at", models.DateTimeField()), ("consumed_at", models.DateTimeField(blank=True, null=True)), ("ip_address", models.GenericIPAddressField(blank=True, null=True)), ("user_agent", models.TextField(blank=True)), ("request_id", models.CharField(blank=True, max_length=64)),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bid_confirmations", to="boards.board")), ("message_validation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="moderation.messagevalidation")), ("represented_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="schools.entity")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bid_confirmations", to="accounts.userprofile")),
            ],
        ),
        migrations.AddField(model_name="bid", name="confirmation", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bids", to="bidding.bidconfirmation")),
        migrations.AddIndex(model_name="bidconfirmation", index=models.Index(fields=["user", "-shown_at"], name="bidding_bid_user_id_7161d8_idx")),
        migrations.AddIndex(model_name="bidconfirmation", index=models.Index(fields=["expires_at"], name="bidding_bid_expires_d1524e_idx")),
    ]
