# Generated by Django 5.2.17 on 2026-09-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_age_acknowledgement'),
        ('bidding', '0009_bidriskconfig_bid_stripe_dispute_id_bidconfirmation_and_more'),
        ('boards', '0007_remove_boardtakeover_boards_boar_represe_b9905b_idx_and_more'),
        ('leaderboard', '0004_remove_competitionperiod_leaderboard_year_e595e7_idx_and_more'),
        ('moderation', '0005_alter_messagevalidation_represented_entity'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='payment_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', '-payment_failed_at'], name='bidding_bid_bidder__6fbe80_idx'),
        ),
    ]
