# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cognito_sub",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
