# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_cognito_sub"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                Lower("display_name"),
                name="accounts_unique_display_name_ci",
            ),
        ),
    ]
