# Generated by Django 5.2.17 on 2026-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_favorite_entity'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='schools.entity'),
        ),
    ]
