# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0006_alter_userprofile_favorite_entity")]

    operations = [
        migrations.AddField(model_name="userprofile", name="dispute_count", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="userprofile", name="last_dispute_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="userprofile", name="has_open_dispute", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="userprofile", name="paid_bidding_suspended", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="userprofile", name="refund_count", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="userprofile", name="risk_tier", field=models.CharField(choices=[("new", "New"), ("established", "Established"), ("trusted", "Trusted"), ("restricted", "Restricted"), ("suspended", "Suspended")], default="new", max_length=16)),
        migrations.AddField(model_name="userprofile", name="successful_bid_count", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="userprofile", name="terms_accepted_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="userprofile", name="terms_version", field=models.CharField(blank=True, max_length=50)),
    ]
