# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rivalry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_a', to='schools.school')),
                ('school_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_b', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'rivalries',
                'indexes': [models.Index(fields=['slug'], name='rivalries_r_slug_c60757_idx'), models.Index(fields=['active', 'name'], name='rivalries_r_active_3e3b11_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rivalry',
            constraint=models.UniqueConstraint(fields=('school_a', 'school_b'), name='unique_rivalry_pair'),
        ),
    ]
