# Generated by Django 5.2.17 on 2026-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivalries', '0002_rivalry_entities'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rivalry',
            name='unique_rivalry_pair',
        ),
        migrations.AlterField(
            model_name='rivalry',
            name='entity_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_a', to='schools.entity'),
        ),
        migrations.AlterField(
            model_name='rivalry',
            name='entity_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_b', to='schools.entity'),
        ),
        migrations.AddConstraint(
            model_name='rivalry',
            constraint=models.UniqueConstraint(fields=('entity_a', 'entity_b'), name='unique_rivalry_pair'),
        ),
    ]
