# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_bid_increment_cents', models.PositiveIntegerField(default=100)),
                ('maximum_bid_cents', models.PositiveIntegerField(default=50000)),
                ('message_max_length', models.PositiveIntegerField(default=80)),
                ('message_validation_expiration_minutes', models.PositiveIntegerField(default=10)),
                ('bidding_enabled', models.BooleanField(default=True)),
                ('moderation_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'game configuration',
                'verbose_name_plural': 'game configuration',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.board')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
            ],
            options={
                'verbose_name_plural': 'activity',
                'indexes': [models.Index(fields=['type', '-created_at'], name='core_activi_type_94ae35_idx'), models.Index(fields=['board', '-created_at'], name='core_activi_board_i_ace3eb_idx')],
            },
        ),
    ]
