# Generated by Django 5.2.17 on 2026-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='guaranteed_display_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
