# Generated by Django 5.2.17 on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_favorite_entity"),
        ("boards", "0007_remove_boardtakeover_boards_boar_represe_b9905b_idx_and_more"),
        ("core", "0002_gameconfig_guaranteed_display_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("last_visited_at", models.DateTimeField(auto_now=True)),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profile_visits", to="boards.board")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="board_visits", to="accounts.userprofile")),
            ],
        ),
        migrations.AddConstraint(
            model_name="boardvisit",
            constraint=models.UniqueConstraint(fields=("profile", "board"), name="core_unique_profile_board_visit"),
        ),
        migrations.AddIndex(
            model_name="boardvisit",
            index=models.Index(fields=["profile", "-visit_count", "-last_visited_at"], name="core_boardv_profile_fbf9ca_idx"),
        ),
    ]
