# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('boards', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.CharField(max_length=80)),
                ('message_hash', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('review', 'Review')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('represented_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='moderation__user_id_0a7aae_idx'), models.Index(fields=['board', '-created_at'], name='moderation__board_i_ac181c_idx'), models.Index(fields=['decision', '-created_at'], name='moderation__decisio_66e4a4_idx'), models.Index(fields=['expires_at'], name='moderation__expires_8c18c5_idx')],
            },
        ),
    ]
