# Generated by Django 5.2 on 2026-08-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagevalidation",
            name="classifier_version",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="messagevalidation",
            name="content_retention_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagevalidation",
            name="policy_version",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.CreateModel(
            name="DisplayNameValidation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=40)),
                ("candidate_hash", models.CharField(max_length=64)),
                ("decision", models.CharField(choices=[("allow", "Allow"), ("block", "Block"), ("review", "Review")], max_length=20)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("confidence", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("policy_version", models.CharField(max_length=32)),
                ("classifier_version", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("content_retention_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="moderation__user_id_d7868e_idx"),
                    models.Index(fields=["decision", "-created_at"], name="moderation__decisio_873d7a_idx"),
                    models.Index(fields=["expires_at"], name="moderation__expires_c49855_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationActionAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(max_length=40)),
                ("target_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="moderation_actions", to="auth.user")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
