# Generated by Django 5.2.17 on 2026-08-30 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_display_name_case_insensitive'),
        ('bidding', '0006_bid_message_validation'),
        ('boards', '0005_boardtakeover_public_id'),
        ('moderation', '0002_moderation_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('removed', 'Removed')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_reported_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_message_report_cases', to=settings.AUTH_USER_MODEL)),
                ('takeover', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report_case', to='boards.boardtakeover')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('hate_speech', 'Hate speech or slur'), ('threats_violence', 'Threats or violence'), ('personal_information', 'Personal information or doxxing'), ('harassment_sexual', 'Harassment or sexual content'), ('spam_advertising', 'Spam or advertising'), ('impersonation', 'Impersonation'), ('other_guidelines', 'Other community-guideline violation')], max_length=40)),
                ('reporter_ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reports', to='accounts.userprofile')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='moderation.messagereportcase')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationPaymentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation', models.CharField(choices=[('cancel_authorization', 'Cancel authorization'), ('refund', 'Refund')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('not_required', 'Not required'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_payment_action', to='bidding.bid')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_actions', to='moderation.messagereportcase')),
            ],
        ),
        migrations.AddIndex(
            model_name='messagereportcase',
            index=models.Index(fields=['status', '-last_reported_at'], name='moderation__status_17737f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereportcase',
            index=models.Index(fields=['resolved_by', '-resolved_at'], name='moderation__resolve_85ae8a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['case', 'category'], name='moderation__case_id_af659a_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('case', 'reporter'), name='unique_reporter_per_message_case'),
        ),
        migrations.AddConstraint(
            model_name='moderationpaymentaction',
            constraint=models.UniqueConstraint(fields=('case', 'bid'), name='unique_payment_action_per_case_bid'),
        ),
    ]
