# Generated by Django 5.2.17 on 2026-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_messagevalidation_represented_entity'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagevalidation',
            name='represented_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.entity'),
        ),
    ]
