# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolWeekStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend_cents', models.BigIntegerField(default=0)),
                ('takeovers', models.PositiveIntegerField(default=0)),
                ('boards_attacked', models.PositiveIntegerField(default=0)),
                ('biggest_bid_cents', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['active', '-starts_at'], name='leaderboard_active_0848bd_idx'), models.Index(fields=['year', 'week_number'], name='leaderboard_year_e595e7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='seasonweek',
            constraint=models.UniqueConstraint(fields=('year', 'week_number'), name='unique_season_week'),
        ),
        migrations.AddField(
            model_name='schoolweekstats',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolweekstats',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonweek'),
        ),
        migrations.AddIndex(
            model_name='schoolweekstats',
            index=models.Index(fields=['school', 'week'], name='leaderboard_school__4d5dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolweekstats',
            index=models.Index(fields=['week', '-total_spend_cents'], name='leaderboard_week_id_0123be_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolweekstats',
            constraint=models.UniqueConstraint(fields=('school', 'week'), name='unique_school_week'),
        ),
    ]
