# Generated by Django 5.2.17 on 2026-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_competition_period_entity_period_stats'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='competitionperiod',
            name='leaderboard_year_e595e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='entityperiodstats',
            name='leaderboard_school__4d5dc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='entityperiodstats',
            name='leaderboard_week_id_0123be_idx',
        ),
        migrations.RenameIndex(
            model_name='competitionperiod',
            new_name='leaderboard_active_1c9e31_idx',
            old_name='leaderboard_active_0848bd_idx',
        ),
        migrations.AlterField(
            model_name='entityperiodstats',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.entity'),
        ),
        migrations.AddIndex(
            model_name='competitionperiod',
            index=models.Index(fields=['competition', 'year', 'week_number'], name='leaderboard_competi_525ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='entityperiodstats',
            index=models.Index(fields=['entity', 'period'], name='leaderboard_entity__444f80_idx'),
        ),
        migrations.AddIndex(
            model_name='entityperiodstats',
            index=models.Index(fields=['period', '-total_spend_cents'], name='leaderboard_period__57ee3f_idx'),
        ),
    ]
