# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('schools', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount_cents', models.PositiveIntegerField(default=0)),
                ('current_message', models.CharField(blank=True, default='THIS BOARD IS OPEN.', max_length=80)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('bidding_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bidding.bid')),
                ('current_controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_boards', to='accounts.userprofile')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='BoardTakeover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=80)),
                ('amount_cents', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='takeover', to='bidding.bid')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeovers', to='boards.board')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
                ('previous_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bidding.bid')),
                ('represented_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['board', '-occurred_at'], name='boards_boar_board_i_6dc817_idx'), models.Index(fields=['represented_school', '-occurred_at'], name='boards_boar_represe_b9905b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['-current_amount_cents'], name='boards_boar_current_9a37e8_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['bidding_enabled'], name='boards_boar_bidding_00f90c_idx'),
        ),
    ]
