# Generated by Django 5.2.17 on 2026-08-28 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bidding', '0004_bid_canceled_at'),
        ('boards', '0002_takeover_history_snapshots'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='guaranteed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='pending_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_on_boards', to='bidding.bid'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['guaranteed_until'], name='boards_boar_guarant_aace61_idx'),
        ),
    ]
