# Generated by Django 5.2.17 on 2026-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_favorite_entity'),
        ('bidding', '0008_remove_bid_bidding_bid_represe_7873c3_idx_and_more'),
        ('boards', '0006_entity_competition_period'),
        ('leaderboard', '0004_remove_competitionperiod_leaderboard_year_e595e7_idx_and_more'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'DROP INDEX IF EXISTS "boards_boar_represe_b9905b_idx"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='boardtakeover',
                    name='boards_boar_represe_b9905b_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='schools.entity'),
        ),
        migrations.AlterField(
            model_name='boardtakeover',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='takeovers', to='leaderboard.competitionperiod'),
        ),
        migrations.AlterField(
            model_name='boardtakeover',
            name='represented_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.entity'),
        ),
        migrations.AddIndex(
            model_name='boardtakeover',
            index=models.Index(fields=['represented_entity', '-occurred_at'], name='boards_boar_represe_d78198_idx'),
        ),
    ]
