# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('schools', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', '-received_at'], name='payments_st_event_t_ba23c4_idx'), models.Index(fields=['processed_at'], name='payments_st_process_ac07c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bid_capture', 'Bid capture'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('adjustment', 'Adjustment')], max_length=30)),
                ('amount_cents', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.bid')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['school', '-created_at'], name='payments_le_school__3bb313_idx'), models.Index(fields=['user', '-created_at'], name='payments_le_user_id_bf2357_idx'), models.Index(fields=['bid'], name='payments_le_bid_id_fed654_idx'), models.Index(fields=['type', '-created_at'], name='payments_le_type_be73d2_idx')],
            },
        ),
    ]
