# Generated by Django 5.2.17 on 2026-08-30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidding", "0006_bid_message_validation"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCapture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_payment_intent_id", models.CharField(max_length=255, unique=True)),
                ("stripe_charge_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("stripe_balance_transaction_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("gross_amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("stripe_fee_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("net_amount_cents", models.IntegerField(blank=True, null=True)),
                ("fee_details", models.JSONField(blank=True, default=list)),
                (
                    "fee_status",
                    models.CharField(
                        choices=[("pending", "Pending Stripe fee data"), ("available", "Stripe fee data available")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("fee_available_at", models.DateTimeField(blank=True, null=True)),
                ("fee_reconciliation_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("fee_reconciliation_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_capture",
                        to="bidding.bid",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fee_status", "fee_reconciliation_attempted_at"],
                        name="payments_pa_fee_sta_0c6343_idx",
                    ),
                    models.Index(fields=["-captured_at"], name="payments_pa_capture_376609_idx"),
                ],
            },
        ),
    ]
