# Generated by Django 5.2.17 on 2026-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_favorite_entity'),
        ('bidding', '0008_remove_bid_bidding_bid_represe_7873c3_idx_and_more'),
        ('payments', '0003_ledgerentry_entity'),
        ('schools', '0003_rename_schools_ent_competi_50d3a0_idx_schools_ent_competi_34e635_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='payments_le_school__3bb313_idx',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.entity'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entity', '-created_at'], name='payments_le_entity__5c16cc_idx'),
        ),
    ]
