# Generated by Django 5.2.17 on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bidding", "0009_bidriskconfig_bid_stripe_dispute_id_bidconfirmation_and_more"), ("payments", "0004_remove_ledgerentry_payments_le_school__3bb313_idx_and_more")]

    operations = [
        migrations.CreateModel(
            name="PurchaseEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("cognito_sub", models.CharField(max_length=128)), ("email", models.EmailField(max_length=254)), ("display_name", models.CharField(blank=True, max_length=40)), ("board_name", models.CharField(max_length=120)), ("ip_address", models.GenericIPAddressField(blank=True, null=True)), ("user_agent", models.TextField(blank=True)), ("request_id", models.CharField(blank=True, max_length=64)), ("terms_version", models.CharField(blank=True, max_length=50)), ("terms_accepted_at", models.DateTimeField(blank=True, null=True)), ("confirmation_version", models.CharField(blank=True, max_length=50)), ("risk_tier_at_purchase", models.CharField(max_length=20)), ("published_at", models.DateTimeField(blank=True, null=True)), ("guaranteed_until", models.DateTimeField(blank=True, null=True)), ("ended_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bid", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_evidence", to="bidding.bid")), ("confirmation", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="purchase_evidence", to="bidding.bidconfirmation")),
            ], options={"indexes": [models.Index(fields=["-published_at"], name="payments_pu_publish_b89935_idx")]},
        ),
    ]
