# Generated by Django 4.2.27 on 2026-08-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('conference', models.CharField(blank=True, max_length=50)),
                ('accent_color', models.CharField(max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='schools_sch_slug_51c325_idx'), models.Index(fields=['active', 'name'], name='schools_sch_active_407608_idx')],
            },
        ),
    ]
