# Generated by Django 5.2.17 on 2026-08-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_competition_entity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entity',
            new_name='schools_ent_competi_34e635_idx',
            old_name='schools_ent_competi_50d3a0_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='schools_ent_competi_776fe4_idx',
            old_name='schools_ent_competi_84c790_idx',
        ),
    ]
